# Dockerfile.frontend
FROM node:18

WORKDIR /app

# Install frontend dependencies
COPY package*.json ./
RUN npm install --legacy-peer-deps

# Copy the rest of the frontend code
COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]