version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=development
      - MONGODB_URI=mongodb+srv://dev1229050403:Nt0CyWjvpAAQsCdQ@cluster0.w7ofgld.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=your_jwt_secret_key_here
      - JWT_EXPIRE=7d
      - JWT_COOKIE_EXPIRE=7
      - FRONTEND_URL=http://localhost:3000

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000/api
    depends_on:
      - backend
