# docker.backend
FROM node:18

WORKDIR /app

# Install backend dependencies
COPY backend/package*.json ./
RUN npm install

# Copy the rest of the backend code
COPY backend/ .

EXPOSE 5000

CMD ["npm", "run", "dev"]
